version: '3.0'

services:
  nestapp:
    container_name: home-library
    image: ed/home-library:1.0.0
    build:
      context: .
    env_file:
      - .env
    ports:
      - '4000:4000'
    command: npm run start:prod
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
